//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAMM.Signer.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAMM.Signer.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient&apos;s certificate not found..
        /// </summary>
        public static string EncryptCeriticateNotFound {
            get {
                return ResourceManager.GetString("EncryptCeriticateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient&apos;s certificate not selected..
        /// </summary>
        public static string EncryptCeriticateNotSelected {
            get {
                return ResourceManager.GetString("EncryptCeriticateNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file &apos;{0}&apos; does not exist..
        /// </summary>
        public static string InputFileDoesNotExist {
            get {
                return ResourceManager.GetString("InputFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input list file &apos;{0}&apos; does not exist..
        /// </summary>
        public static string InputListFileDoesNotExist {
            get {
                return ResourceManager.GetString("InputListFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file specification is missing..
        /// </summary>
        public static string InputSpecMissing {
            get {
                return ResourceManager.GetString("InputSpecMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output files extension format &apos;{0}&apos;..
        /// </summary>
        public static string InvalidOutputFileExtension {
            get {
                return ResourceManager.GetString("InvalidOutputFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one certificate with thumbprint &apos;{0}&apos; found..
        /// </summary>
        public static string MultipleCertificates {
            get {
                return ResourceManager.GetString("MultipleCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must have a name (&apos;{0}&apos;)..
        /// </summary>
        public static string NamelessParameter {
            get {
                return ResourceManager.GetString("NamelessParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument value &apos;{0}&apos; without parameter name..
        /// </summary>
        public static string ParameterMissing {
            get {
                return ResourceManager.GetString("ParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected certificate is missing private key..
        /// </summary>
        public static string PrivateKeyMissing {
            get {
                return ResourceManager.GetString("PrivateKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured:
        ///{0}.
        /// </summary>
        public static string ReportError {
            get {
                return ResourceManager.GetString("ReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has not been processed..
        /// </summary>
        public static string ReportFileNotProcessed {
            get {
                return ResourceManager.GetString("ReportFileNotProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: DECRYPTION
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is not valid.
        ///Time of signature: NOT APPLICABLE..
        /// </summary>
        public static string ReportInvalidDecryptCert {
            get {
                return ResourceManager.GetString("ReportInvalidDecryptCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: ENCRYPTION
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is not valid.
        ///Time of signature: NOT APPLICABLE..
        /// </summary>
        public static string ReportInvalidEncryptCert {
            get {
                return ResourceManager.GetString("ReportInvalidEncryptCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: DIGITAL SIGNATURE
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is not valid.
        ///Time of signature: {2}.
        /// </summary>
        public static string ReportInvalidSignCert {
            get {
                return ResourceManager.GetString("ReportInvalidSignCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing file &apos;{0}&apos;:
        ///{1}.
        /// </summary>
        public static string ReportOpError {
            get {
                return ResourceManager.GetString("ReportOpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed files: {0}..
        /// </summary>
        public static string ReportOpPreamble {
            get {
                return ResourceManager.GetString("ReportOpPreamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: DECRYPTION
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is valid.
        ///Time of signature: NOT APPLICABLE..
        /// </summary>
        public static string ReportValidDecryptCert {
            get {
                return ResourceManager.GetString("ReportValidDecryptCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: ENCRYPTION
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is valid.
        ///Time of signature: NOT APPLICABLE..
        /// </summary>
        public static string ReportValidEncryptCert {
            get {
                return ResourceManager.GetString("ReportValidEncryptCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: DIGITAL SIGNATURE
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is valid.
        ///Time of signature: {2}.
        /// </summary>
        public static string ReportValidSignCert {
            get {
                return ResourceManager.GetString("ReportValidSignCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File signature have been verified..
        /// </summary>
        public static string ReportVerified {
            get {
                return ResourceManager.GetString("ReportVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was decrypted and signatures have been verified..
        /// </summary>
        public static string ReportVerifiedAndDecrypted {
            get {
                return ResourceManager.GetString("ReportVerifiedAndDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select recipient&apos;s identification certificate..
        /// </summary>
        public static string SelectEncryptCertificateMessage {
            get {
                return ResourceManager.GetString("SelectEncryptCertificateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        public static string SelectEncryptCertificateTitle {
            get {
                return ResourceManager.GetString("SelectEncryptCertificateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your signature certificate..
        /// </summary>
        public static string SelectSignCertificateMessage {
            get {
                return ResourceManager.GetString("SelectSignCertificateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing.
        /// </summary>
        public static string SelectSignCertificateTitle {
            get {
                return ResourceManager.GetString("SelectSignCertificateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature certificate not found..
        /// </summary>
        public static string SignCeriticateNotFound {
            get {
                return ResourceManager.GetString("SignCeriticateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature certificate not selected..
        /// </summary>
        public static string SignCeriticateNotSelected {
            get {
                return ResourceManager.GetString("SignCeriticateNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many program arguments specified: expected {0}, actual {1}..
        /// </summary>
        public static string TooManyArguments {
            get {
                return ResourceManager.GetString("TooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying PKCS #7 data type &apos;{0}&apos; is not supported or data type has no signature..
        /// </summary>
        public static string WrongSignVerificationDataType {
            get {
                return ResourceManager.GetString("WrongSignVerificationDataType", resourceCulture);
            }
        }
    }
}
