//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAMM.Signer.Pkcs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAMM.Signer.Pkcs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported content (degenerated signature data)..
        /// </summary>
        public static string DegenerateSignature {
            get {
                return ResourceManager.GetString("DegenerateSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid content state for this operation; expected &apos;{0}&apos;, actual &apos;{1}&apos;..
        /// </summary>
        public static string InvalidContentState {
            get {
                return ResourceManager.GetString("InvalidContentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recipients with supported identification type (total recipients: {0})..
        /// </summary>
        public static string NoIdentifiableRecipients {
            get {
                return ResourceManager.GetString("NoIdentifiableRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signers with supported identification type (total signers: {0})..
        /// </summary>
        public static string NoIdentifiableSigners {
            get {
                return ResourceManager.GetString("NoIdentifiableSigners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate serial number &apos;{1}&apos; issued by &apos;{0}&apos; does not have private key..
        /// </summary>
        public static string PrivateKeyMissing {
            get {
                return ResourceManager.GetString("PrivateKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message is not signed..
        /// </summary>
        public static string SignatureRequired {
            get {
                return ResourceManager.GetString("SignatureRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single message recipient is supported and required, actual number is {0}..
        /// </summary>
        public static string SingleRecipientRequired {
            get {
                return ResourceManager.GetString("SingleRecipientRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exactly one message signer is required, actual number is {0}..
        /// </summary>
        public static string SingleSignerRequired {
            get {
                return ResourceManager.GetString("SingleSignerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message is not addressed to a recipient with certificate serial number &apos;{1}&apos; issued by &apos;{0}&apos;..
        /// </summary>
        public static string UnknownRecipient {
            get {
                return ResourceManager.GetString("UnknownRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS content type &apos;{0}&apos; is not supported..
        /// </summary>
        public static string UnsupportedCmsContentType {
            get {
                return ResourceManager.GetString("UnsupportedCmsContentType", resourceCulture);
            }
        }
    }
}
