//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAMM.Signer.Interop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAMM.Signer.Interop.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported destination array element variant type {0} specified when converting byte array for automation..
        /// </summary>
        internal static string ComHelpers_Convert_InvalidVarType {
            get {
                return ResourceManager.GetString("ComHelpers_Convert_InvalidVarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid certificate object..
        /// </summary>
        internal static string CoPkcs7_InvalidCertificateObject {
            get {
                return ResourceManager.GetString("CoPkcs7_InvalidCertificateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuppored data array variant type..
        /// </summary>
        internal static string CoPkcs7_InvalidDataType {
            get {
                return ResourceManager.GetString("CoPkcs7_InvalidDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate is missing from internal certificate map..
        /// </summary>
        internal static string CoPkcs7_MissingCertificate {
            get {
                return ResourceManager.GetString("CoPkcs7_MissingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient certificate not specified..
        /// </summary>
        internal static string CoPkcs7_RecipientNotSpecified {
            get {
                return ResourceManager.GetString("CoPkcs7_RecipientNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature certificate has not been specified..
        /// </summary>
        internal static string CoPkcs7_SignerNotSpecified {
            get {
                return ResourceManager.GetString("CoPkcs7_SignerNotSpecified", resourceCulture);
            }
        }
    }
}
