//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAMM.Signer.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAMM.Signer.Cli.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured:
        ///{0}.
        /// </summary>
        public static string ReportError {
            get {
                return ResourceManager.GetString("ReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: ENCRYPTION
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is not valid.
        ///Time of signature: NOT APPLICABLE..
        /// </summary>
        public static string ReportInvalidEncryptCert {
            get {
                return ResourceManager.GetString("ReportInvalidEncryptCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: DIGITAL SIGNATURE
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is not valid.
        ///Time of signature: {2}.
        /// </summary>
        public static string ReportInvalidSignCert {
            get {
                return ResourceManager.GetString("ReportInvalidSignCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing file &apos;{0}&apos;:
        ///{1}.
        /// </summary>
        public static string ReportOpError {
            get {
                return ResourceManager.GetString("ReportOpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files are successfully signed and/or encrypted:.
        /// </summary>
        public static string ReportOpPreamble {
            get {
                return ResourceManager.GetString("ReportOpPreamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: ENCRYPTION
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is valid.
        ///Time of signature: NOT APPLICABLE..
        /// </summary>
        public static string ReportValidEncryptCert {
            get {
                return ResourceManager.GetString("ReportValidEncryptCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: DIGITAL SIGNATURE
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is valid.
        ///Time of signature: {2}.
        /// </summary>
        public static string ReportValidSignCert {
            get {
                return ResourceManager.GetString("ReportValidSignCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception:.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
    }
}
