//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAMM.Signer.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAMM.Signer.Gui.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: ENCRYPTION
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is not valid.
        ///Time of signature: NOT APPLICABLE..
        /// </summary>
        internal static string MainWindow_FileList_ReportInvalidEncryptCert {
            get {
                return ResourceManager.GetString("MainWindow_FileList_ReportInvalidEncryptCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: DIGITAL SIGNATURE
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is not valid.
        ///Time of signature: {2}.
        /// </summary>
        internal static string MainWindow_FileList_ReportInvalidSignCert {
            get {
                return ResourceManager.GetString("MainWindow_FileList_ReportInvalidSignCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: ENCRYPTION
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is valid.
        ///Time of signature: NOT APPLICABLE..
        /// </summary>
        internal static string MainWindow_FileList_ReportValidEncryptCert {
            get {
                return ResourceManager.GetString("MainWindow_FileList_ReportValidEncryptCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose: DIGITAL SIGNATURE
        ///Friendly name: &apos;{0}&apos;
        ///Subject: &apos;{1}&apos;
        ///Certificate is valid.
        ///Time of signature: {2}.
        /// </summary>
        internal static string MainWindow_FileList_ReportValidSignCert {
            get {
                return ResourceManager.GetString("MainWindow_FileList_ReportValidSignCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Files.
        /// </summary>
        internal static string MainWindow_LoadButton_FileOpenDialogTitle {
            get {
                return ResourceManager.GetString("MainWindow_LoadButton_FileOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured:
        ///{0}.
        /// </summary>
        internal static string MainWindow_ReportError {
            get {
                return ResourceManager.GetString("MainWindow_ReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing file &apos;{0}&apos;:
        ///{1}.
        /// </summary>
        internal static string MainWindow_ReportOpError {
            get {
                return ResourceManager.GetString("MainWindow_ReportOpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to encrypt the files(s)?.
        /// </summary>
        internal static string MainWindow_SignButton_EncryptPrompt {
            get {
                return ResourceManager.GetString("MainWindow_SignButton_EncryptPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select certificate for encrypting and decrypting files. .
        /// </summary>
        internal static string OptionsDialog_SelectEncryptCertificateMessage {
            get {
                return ResourceManager.GetString("OptionsDialog_SelectEncryptCertificateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient certificate.
        /// </summary>
        internal static string OptionsDialog_SelectEncryptCertificateTitle {
            get {
                return ResourceManager.GetString("OptionsDialog_SelectEncryptCertificateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the certificate for signing files. .
        /// </summary>
        internal static string OptionsDialog_SelectSignCertificateMessage {
            get {
                return ResourceManager.GetString("OptionsDialog_SelectSignCertificateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature certificate.
        /// </summary>
        internal static string OptionsDialog_SelectSignCertificateTitle {
            get {
                return ResourceManager.GetString("OptionsDialog_SelectSignCertificateTitle", resourceCulture);
            }
        }
    }
}
